name: Run Tests Manually

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Adjust based on your project's dependencies

    - name: Run tests
      run: |
        pytest  # Adjust based on your testing framework and test file locations
